name: Deploy on Push

on:
  push:
    branches: [develop, release, main]

jobs:
  dev:
    name: deploy cloudrun to dev environment
    if: ${{ github.ref == 'refs/heads/develop' || github.base_ref == 'develop' }}
    uses: ./.github/workflows/_deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: Development
      ref: ${{ github.sha }}
    secrets: inherit
  stage:
    if: ${{ github.ref == 'refs/heads/release' || github.base_ref == 'release' }}
    uses: ./.github/workflows/_deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: Regression
      ref: ${{ github.sha }}
    secrets: inherit
  prod:
    if: ${{ github.ref == 'refs/heads/main' || github.base_ref == 'main' }}
    uses: ./.github/workflows/_deploy.yml
    permissions:
      id-token: write
      contents: read
    with:
      environment: Production
      ref: ${{ github.sha }}
    secrets: inherit
